services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hack_party_2026
      POSTGRES_PASSWORD: "ObvPjxKwQLJtcE3yIFcx039DnQ1byB_C"
    volumes:
      - hack_party_2026_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "_qqTyOIbROnQbXluAGZPj8C5IUyp359J"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hack_party_2026_test
      POSTGRES_PASSWORD: "F8pS-FKWRjd9IUEY-gUeyBSwSxb2Tinu"
    volumes:
      - hack_party_2026_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "htTT0nKqCv66IzlG3X7M-kDwf9uYPCwf"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  hack_party_2026_data:
  hack_party_2026_test_data:
