services:
  # Serverpod server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"  # API port
      - "8081:8081"  # Insights port
      - "8082:8082"  # Web server port
    environment:
      runmode: production
      serverid: default
      logging: normal
      role: monolith
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # PostgreSQL database
  postgres:
    image: pgvector/pgvector:pg16
    expose:
      - "5432"  # Internal only, not exposed to host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hack_party_2026
      POSTGRES_PASSWORD: "C-whI1HZFNnEcMXDCdaGbjFmYiI2FY68fasr3eqww"
    volumes:
      - hack_party_2026_prod_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis cache
  redis:
    image: redis:6.2.6
    expose:
      - "6379"  # Internal only, not exposed to host
    command: redis-server --requirepass "GCSOvVn5widFzk-4XLbyqo-pCm-12331safd"
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped

volumes:
  hack_party_2026_prod_data:

